[project]
name = "urltoqr"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "pillow>=12.0.0",
    "qrcode>=8.2",
    "slack-bolt>=1.26.0",
    "slack-sdk>=3.37.0",
]
